### ISSUE TITLE
Question about code release

### ISSUE THREAD

**Issue by SejeongPark8354** [AtomwiseInc/cslvae#1]
First of all, your research was so impressive to me. Thank you. 

Can you tell me your plan about CSLVAE code release?! 
If you can share your code publicly, it will be very helpful for my research. 
Thank you again.

**Comment by aryanpedawi** [comment]
Hi @SejeongPark8354, thank you for your comment! The code is now available in GitHub.

**Comment by SejeongPark8354** [comment]
Dear @aryanpedawi 
Thanks for the update. This update will be very helpful in my research.
